name: Publish Package

on:
  release:
    types: [created]

jobs:
  npm-publish:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: npm publish --access public --scope @prgm ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
